### ISSUE TITLE
v1.0 roadmap

### ISSUE THREAD

**Issue by Yuyz0112** [webzard-io/CLI2UI#33]
- Core Feature
  - [ ] Preset envs
- UX
  - [x] Improve the dry run result modal UX
- Bugfix
  - [x] Bug: args need priority otherwise the order might be wrong
- Misc
  - examples
    - [x] docker
    - [x] ping
    - [x] kail
  - [ ] a simple logo
  - [ ] a blog to introduce CLI2UI

**Comment by Yuyz0112** [comment]
An example UX of the dry run result modal:

![image](https://github.com/webzard-io/CLI2UI/assets/13651389/ab365904-28fa-42a5-9faf-26b20936e52a)

**Comment by Kiyo5hi** [comment]
Bug: args need priority otherwise the order might be wrong

**Comment by Kiyo5hi** [comment]
Feat: preset envs
